# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pocplayermobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pocplayermobile

  pod 'JWPlayer-SDK', '~> 3.6.1'

end

target 'pocplayermobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pocplayermobile-tvOS

  target 'pocplayermobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
